### ISSUE TITLE
Add woocommerce_product_meta_end

### ISSUE THREAD

**Issue by UVLabs** [miya0001/atom-wordpress-dictionary#1]
I think you are missing this hook in your dictionary.

http://hookr.io/actions/woocommerce_product_meta_end/

**Comment by miya0001** [comment]
It is WooCommerce plugin's hook.

**Comment by UVLabs** [comment]
Yes I know, but as I could see you have woocommerce hooks already incorporated but not all, so just pointing out that you're missing that one, as well as a few others.

**Comment by miya0001** [comment]
> but as I could see you have woocommerce hooks already incorporated

Oh, I guess I made a mistake, Thanks. :smile:

**Comment by UVLabs** [comment]
Or maybe it was me :3 I just actually checked your source code and noticed you have no actions for woocommerce in there...I wonder why atom recommended those I have no other dictionary packages installed.

I will close this.
